# Generated by Django 4.0.3 on 2022-09-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_field',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
